# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArcheoSync
                                 A QGIS plugin
 This plugin allows archaeologists to prepare data for the field and to import it back into the project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Elisa Caron-Laviolette
        email                : elisa.laviolette@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
from typing import List, Optional, Dict

from qgis.PyQt.QtCore import QSettings, QObject, QCoreApplication, QTranslator, QLocale, QTimer
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtWidgets import QDockWidget

# Initialize Qt resources from file resources.py
from .resources import *
from .ui.settings_dialog import SettingsDialog
from .ui.prepare_recording_dialog import (
    PrepareRecordingDialog,
    PREPARATION_MODE_GLOBAL,
    EXTENT_SOURCE_LAYER,
)
from .ui.import_data_dialog import ImportDataDialog
from .ui.column_mapping_dialog import ColumnMappingDialog
from .services import (
    QGISSettingsManager,
    QGISFileSystemService,
    ArcheoSyncConfigurationValidator,
    QGISLayerService,
    CSVImportService,
    QGISRasterProcessingService,
    QGISProjectCreationService,
    FieldProjectImportService,
    QGISMapThemeService,
)

# Layer names used for pending imports (must match import summary / field import services).
_TEMPORARY_IMPORT_LAYER_NAMES = (
    "New Objects",
    "New Features",
    "New Small Finds",
    "Imported_CSV_Points",
)


class ArcheoSyncPlugin(QObject):
    """
    ArcheoSync QGIS Plugin.
    
    All user-facing strings are wrapped in self.tr() for translation.
    """
    
    def __init__(self, iface):
        """
        Initialize the plugin.
        
        Args:
            iface: QGIS interface instance
        """
        QObject.__init__(self)
        self._iface = iface
        self._plugin_dir = os.path.dirname(__file__)
        
        # --- TRANSLATION LOADING LOGIC ---
        self._translator = None
        locale = QSettings().value('locale/userLocale', QLocale().name())[:2]
        qm_filename = f'ArcheoSyncPlugin_{locale}.qm'
        locale_path = os.path.join(self._plugin_dir, 'i18n', qm_filename)
        if os.path.exists(locale_path):
            self._translator = QTranslator()
            if self._translator.load(locale_path):
                QCoreApplication.installTranslator(self._translator)
            else:
                print(f"Failed to load translation file: {locale_path}")
        else:
            print(f"Translation file does not exist: {locale_path}")
        # --- END TRANSLATION LOADING LOGIC ---
        
        # Initialize services using dependency injection
        self._initialize_services()
        
        # Plugin state
        self._actions: List[QAction] = []
        self._first_start = True
        self._settings_dialog: Optional[SettingsDialog] = None
        self._import_data_dialog: Optional[ImportDataDialog] = None
    
    def _initialize_services(self) -> None:
        """Initialize all required services."""
        # Initialize settings manager
        self._settings_manager = QGISSettingsManager('ArcheoSync')
        
        # Initialize file system service
        self._file_system_service = QGISFileSystemService(self._iface.mainWindow())
        
        # Initialize layer service
        self._layer_service = QGISLayerService()

        # Initialize advanced services defensively so plugin activation
        # does not fail entirely if one optional API changed across QGIS versions.
        self._raster_processing_service = None
        self._project_creation_service = None
        self._csv_import_service = None
        self._field_project_import_service = None
        self._map_theme_service = None

        try:
            self._map_theme_service = QGISMapThemeService()
        except Exception as exc:
            print(f"Failed to initialize map theme service: {exc}")

        try:
            self._raster_processing_service = QGISRasterProcessingService()
            self._project_creation_service = QGISProjectCreationService(
                self._settings_manager,
                self._layer_service,
                self._file_system_service,
                self._raster_processing_service
            )
        except Exception as exc:
            print(f"Failed to initialize project creation services: {exc}")

        try:
            self._csv_import_service = CSVImportService(
                self._iface,
                self._file_system_service,
                self._settings_manager,
                self._layer_service,
            )
        except Exception as exc:
            print(f"Failed to initialize CSV import service: {exc}")

        try:
            self._field_project_import_service = FieldProjectImportService(
                self._settings_manager,
                self._layer_service,
                self._file_system_service
            )
        except Exception as exc:
            print(f"Failed to initialize field project import service: {exc}")
        
        # Initialize configuration validator
        self._configuration_validator = ArcheoSyncConfigurationValidator(
            self._file_system_service,
            self._layer_service
        )
    
    def add_action(
        self,
        icon_path: str,
        text: str,
        callback: callable,
        enabled_flag: bool = True,
        add_to_menu: bool = True,
        add_to_toolbar: bool = True,
        status_tip: Optional[str] = None,
        whats_this: Optional[str] = None,
        parent=None
    ) -> QAction:
        """
        Add a toolbar icon to the toolbar.
        
        Args:
            icon_path: Path to the icon for this action
            text: Text that should be shown in menu items for this action
            callback: Function to be called when the action is triggered
            enabled_flag: A flag indicating if the action should be enabled by default
            add_to_menu: Flag indicating whether the action should also be added to the menu
            add_to_toolbar: Flag indicating whether the action should also be added to the toolbar
            status_tip: Optional text to show in a popup when mouse pointer hovers over the action
            whats_this: Optional text to show in the status bar when the action is triggered
            parent: Parent widget for the action
            
        Returns:
            The action that was created
        """
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        
        if status_tip is not None:
            action.setStatusTip(self.tr(status_tip))
        
        if whats_this is not None:
            action.setWhatsThis(self.tr(whats_this))
        
        if add_to_toolbar:
            self._iface.addToolBarIcon(action)
        
        if add_to_menu:
            self._iface.addPluginToMenu(self.tr(u'&ArcheoSync'), action)
        
        self._actions.append(action)
        return action

    @staticmethod
    def _execute_dialog(dialog) -> int:
        """
        Execute a dialog with Qt5/Qt6 compatibility.

        QGIS 3 (Qt5) commonly exposes ``exec_`` while QGIS 4 (Qt6) uses ``exec``.
        This helper keeps one code path compatible with both runtimes.
        """
        exec_method = getattr(dialog, "exec", None)
        if callable(exec_method):
            return exec_method()

        legacy_exec_method = getattr(dialog, "exec_", None)
        if callable(legacy_exec_method):
            return legacy_exec_method()

        raise AttributeError("Dialog has neither exec() nor exec_() method.")
    
    def initGui(self) -> None:
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/archeo_sync/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Configuration'),
            callback=self.run,
            parent=self._iface.mainWindow()
        )
        
        # Add Prepare Recording menu item
        self.add_action(
            icon_path,
            text=self.tr(u'Prepare Recording'),
            callback=self.run_prepare_recording,
            parent=self._iface.mainWindow()
        )
        
        # Add Import Data menu item
        self.add_action(
            icon_path,
            text=self.tr(u'Import Data'),
            callback=self.run_import_data,
            parent=self._iface.mainWindow()
        )
    
    def unload(self) -> None:
        """Remove the plugin menu item and icon from QGIS GUI."""
        for action in self._actions:
            self._iface.removePluginMenu(self.tr(u'&ArcheoSync'), action)
            self._iface.removeToolBarIcon(action)
        # --- TRANSLATION UNLOADING LOGIC ---
        if self._translator:
            QCoreApplication.removeTranslator(self._translator)
            self._translator = None
        # --- END TRANSLATION UNLOADING LOGIC ---
    
    def run(self) -> None:
        """Run method that performs all the real work."""
        # Create the dialog only once
        if self._first_start:
            self._first_start = False
            self._settings_dialog = SettingsDialog(
                settings_manager=self._settings_manager,
                file_system_service=self._file_system_service,
                layer_service=self._layer_service,
                configuration_validator=self._configuration_validator,
                parent=self._iface.mainWindow()
            )
        
        # Show the dialog
        if self._settings_dialog:
            result = self._execute_dialog(self._settings_dialog)
            
            # Handle dialog result
            if result:
                self._handle_settings_accepted()
    
    def _handle_settings_accepted(self) -> None:
        """Handle the case when settings dialog is accepted."""
        # This is where you would implement the actual plugin functionality
        # based on the saved settings
        pass
    
    def run_prepare_recording(self) -> None:
        """Run the prepare recording dialog."""
        if not self._project_creation_service:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Initialization Error"),
                self.tr("Project creation service is unavailable in this QGIS runtime.")
            )
            return

        # Create and show the prepare recording dialog
        dialog = PrepareRecordingDialog(
            layer_service=self._layer_service,
            settings_manager=self._settings_manager,
            parent=self._iface.mainWindow()
        )
        
        result = self._execute_dialog(dialog)
        
        # Handle dialog result
        if result:
            self._handle_prepare_recording_accepted(dialog)
    
    def _handle_prepare_recording_accepted(self, dialog) -> None:
        """Handle the case when prepare recording dialog is accepted."""
        try:
            from qgis.PyQt.QtWidgets import QMessageBox

            recording_areas_layer_id = self._settings_manager.get_value('recording_areas_layer', '')
            objects_layer_id = self._settings_manager.get_value('objects_layer', '')
            features_layer_id = self._settings_manager.get_value('features_layer', '')
            small_finds_layer_id = self._settings_manager.get_value('small_finds_layer', '')
            destination_folder = self._settings_manager.get_value('field_projects_folder', '')

            if not recording_areas_layer_id or not objects_layer_id or not destination_folder:
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Configuration Error"),
                    self.tr("Required configuration is missing. Please check your settings.")
                )
                return

            if dialog.get_preparation_mode() == PREPARATION_MODE_GLOBAL:
                self._handle_global_prepare_recording_accepted(
                    dialog=dialog,
                    destination_folder=destination_folder,
                    recording_areas_layer_id=recording_areas_layer_id,
                )
                return

            # Get selected features and extract their data early to avoid QGIS object deletion issues
            recording_layer = self._layer_service.get_layer_by_id(recording_areas_layer_id)
            if not recording_layer:
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Layer Error"),
                    self.tr("Recording areas layer not found.")
                )
                return
            
            selected_features = recording_layer.selectedFeatures()
            if not selected_features:
                from qgis.PyQt.QtWidgets import QMessageBox
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("No Selection"),
                    self.tr("No recording areas are selected.")
                )
                return
            
            # Extract feature data early to avoid issues with QGIS object deletion
            feature_data = []
            layer_display_expression = recording_layer.displayExpression()
            recording_area_variable_source = self._settings_manager.get_value(
                'recording_area_variable_source',
                'display'
            )
            
            for feature in selected_features:
                # Extract geometry as WKT
                geometry_wkt = None
                if hasattr(feature, 'geometry') and feature.geometry():
                    geom = feature.geometry()
                    if geom and not geom.isNull():
                        geometry_wkt = geom.asWkt()
                
                # Extract attributes as a list to preserve order
                attributes = []
                if hasattr(feature, 'attributes'):
                    attributes = list(feature.attributes())
                
                # Extract feature ID
                feature_id = feature.id() if hasattr(feature, 'id') else None
                
                # Get display name using QGIS expression evaluation
                display_name = str(feature_id)  # Default to feature ID
                if layer_display_expression and layer_display_expression.strip():
                    try:
                        from qgis.core import QgsExpression, QgsExpressionContext, QgsExpressionContextUtils
                        expr = QgsExpression(layer_display_expression)
                        if not expr.hasParserError():
                            context = QgsExpressionContext()
                            context.appendScope(QgsExpressionContextUtils.layerScope(recording_layer))
                            context.setFeature(feature)
                            result = expr.evaluate(context)
                            if result and str(result) != 'NULL' and str(result).strip():
                                display_name = str(result).strip()
                    except Exception as e:
                        print(f"Display expression evaluation failed for feature {feature_id}: {str(e)}")
                        # Fall back to common name fields
                        name_fields = ['name', 'title', 'label', 'description', 'comment']
                        for field_name in name_fields:
                            field_idx = recording_layer.fields().indexOf(field_name)
                            if field_idx >= 0 and field_idx < len(attributes):
                                value = attributes[field_idx]
                                if value and str(value) != 'NULL':
                                    display_name = str(value)
                                    break
                
                feature_data.append({
                    'id': feature_id,
                    'geometry_wkt': geometry_wkt,
                    'attributes': attributes,
                    'display_name': display_name,
                    'recording_area_variable_value': self._resolve_recording_area_variable_value(
                        source=recording_area_variable_source,
                        feature=feature,
                        feature_id=feature_id,
                        display_name=display_name
                    )
                })
            
            # Get next values for all features
            next_values = dialog.get_all_next_values()

            self._apply_configured_map_theme('recording_area_preparation_map_theme')
            
            # Display expression information for debugging
            if layer_display_expression and layer_display_expression.strip():
                print(f"Display expression: '{layer_display_expression}'")
            
            # Process each selected recording area
            success_count = 0
            error_count = 0
            
            for i, feature_info in enumerate(feature_data):
                try:
                    # Use the pre-extracted display name
                    feature_name = feature_info['display_name']
                    
                    # Get level from next values
                    level = next_values[i].get('level', '') if i < len(next_values) else ''
                    
                    # Create project name: display name + '_' + level (if level is defined)
                    if level:
                        project_name = f"{feature_name}_{level}"
                    else:
                        project_name = feature_name
                    
                    # Clean project name for file system
                    import re
                    project_name = re.sub(r'[^\w\-_\.]', '_', project_name)
                    
                    # Get background image from next values
                    background_layer_id = next_values[i]['background_image'] if i < len(next_values) else ''
                    
                    # Get extra layers from settings
                    extra_layers = self._settings_manager.get_value('extra_field_layers', [])
                    
                    # Create field project using the new project creation service
                    success = self._project_creation_service.create_field_project(
                        feature_data=feature_info,
                        recording_areas_layer_id=recording_areas_layer_id,
                        objects_layer_id=objects_layer_id,
                        features_layer_id=features_layer_id if features_layer_id else None,
                        small_finds_layer_id=small_finds_layer_id if small_finds_layer_id else None,
                        background_layer_id=background_layer_id if background_layer_id else None,
                        extra_layers=extra_layers,
                        destination_folder=destination_folder,
                        project_name=project_name,
                        next_values=next_values[i] if i < len(next_values) else {},
                        source_map_rotation=self._iface.mapCanvas().rotation(),
                    )
                    
                    if success:
                        success_count += 1
                    else:
                        error_count += 1
                        
                except Exception as e:
                    feature_id = feature_info.get('id', 'unknown')
                    print(f"Error processing recording area {feature_id}: {str(e)}")
                    error_count += 1
            
            # Show results
            from qgis.PyQt.QtWidgets import QMessageBox
            if error_count == 0:
                QMessageBox.information(
                    self._iface.mainWindow(),
                    self.tr("Field Project Preparation Complete"),
                    self.tr(f"Successfully created {success_count} field project(s) in:\n{destination_folder}")
                )
            else:
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Field Project Preparation Results"),
                    self.tr(f"Created {success_count} field project(s) successfully.\n{error_count} project(s) failed.\n\nCheck the console for error details.")
                )
                
        except Exception as e:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Error"),
                self.tr(f"An error occurred during field project preparation:\n{str(e)}")
            )

    def _handle_global_prepare_recording_accepted(
        self,
        dialog,
        destination_folder: str,
        recording_areas_layer_id: str,
    ) -> None:
        """Create a single global field project from dialog options."""
        from qgis.PyQt.QtWidgets import QMessageBox

        try:
            self._apply_configured_map_theme('global_preparation_map_theme')

            options = dialog.get_global_project_options()
            project_name = options.get('project_name', '').strip()
            if not project_name:
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Validation Error"),
                    self.tr("A project name is required for a global project."),
                )
                return

            import re
            project_name = re.sub(r'[^\w\-_\.]', '_', project_name)

            recording_layer = self._layer_service.get_layer_by_id(recording_areas_layer_id)
            extent_geometry = None
            extent_crs_authid = None
            if options.get('extent_source') == EXTENT_SOURCE_LAYER:
                layer_id = options.get('extent_layer_id', '')
                extent_layer = self._layer_service.get_layer_by_id(layer_id)
                extent_geometry = self._layer_service.resolve_extent_geometry_from_layer(layer_id)
                if extent_layer and extent_layer.crs().isValid():
                    extent_crs_authid = extent_layer.crs().authid()
            else:
                bounds = options.get('manual_bounds') or {}
                crs = recording_layer.crs() if recording_layer else None
                extent_geometry = self._layer_service.resolve_extent_geometry_from_rectangle(
                    bounds.get('xmin', 0),
                    bounds.get('ymin', 0),
                    bounds.get('xmax', 0),
                    bounds.get('ymax', 0),
                    crs=crs,
                )
                if crs and crs.isValid():
                    extent_crs_authid = crs.authid()

            if not extent_geometry or extent_geometry.isNull() or extent_geometry.isEmpty():
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Extent Error"),
                    self.tr("Could not build a valid extent for the global project."),
                )
                return

            success = self._project_creation_service.create_global_field_project(
                extent_geometry_wkt=extent_geometry.asWkt(),
                destination_folder=destination_folder,
                project_name=project_name,
                background_layer_id=None,
                extent_crs_authid=extent_crs_authid,
            )

            if success:
                QMessageBox.information(
                    self._iface.mainWindow(),
                    self.tr("Field Project Preparation Complete"),
                    self.tr(
                        "Successfully created global field project:\n{folder}/{name}"
                    ).format(folder=destination_folder, name=project_name),
                )
            else:
                QMessageBox.warning(
                    self._iface.mainWindow(),
                    self.tr("Field Project Preparation Failed"),
                    self.tr("Failed to create the global field project. Check the console for details."),
                )
        except Exception as e:
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Error"),
                self.tr(f"An error occurred during global project preparation:\n{str(e)}"),
            )

    def _resolve_recording_area_variable_value(self, source: str, feature, feature_id: Optional[int], display_name: str) -> str:
        """
        Resolve the value stored in the project `recording_area` variable.

        Source values:
            - "display": evaluated display expression value
            - "id": feature identifier
            - "field:<name>": value from the specified attribute field
        """
        if source == "id":
            return str(feature_id) if feature_id is not None else display_name

        if isinstance(source, str) and source.startswith("field:"):
            field_name = source.split(":", 1)[1].strip()
            if field_name:
                try:
                    value = feature.attribute(field_name)
                    if value is not None and str(value) != "NULL" and str(value).strip():
                        return str(value).strip()
                except Exception as exc:
                    print(f"Could not resolve recording_area variable from field '{field_name}': {exc}")

        return display_name
    
    def run_import_data(self) -> None:
        """
        Run the import data flow from the menu.

        If temporary import layers are still in the project (import not yet
        validated or cancelled), rebuild the import summary from current layer
        contents and show a new dock (detectors re-run; any previous summary dock
        is replaced). Otherwise open the file/project selection dialog for a new import.
        """
        if not self._csv_import_service or not self._field_project_import_service:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Initialization Error"),
                self.tr("Import services are unavailable in this QGIS runtime.")
            )
            return

        if self._has_pending_import_temporary_layers():
            summary_data = self._summary_data_from_temporary_import_layers()
            self._show_import_summary(
                summary_data,
                archive_csv=bool(self._csv_import_service.get_last_imported_files()),
                archive_projects=bool(
                    self._field_project_import_service.get_last_imported_projects()
                ),
            )
            return

        dialog = ImportDataDialog(
            settings_manager=self._settings_manager,
            file_system_service=self._file_system_service,
            parent=self._iface.mainWindow()
        )

        result = self._execute_dialog(dialog)

        if result:
            self._handle_import_data_accepted(dialog)

    def _has_pending_import_temporary_layers(self) -> bool:
        """True if any ArcheoSync temporary import layer is still in the project."""
        for name in _TEMPORARY_IMPORT_LAYER_NAMES:
            if self._layer_service.get_layer_by_name(name) is not None:
                return True
        return False

    def _summary_data_from_temporary_import_layers(self) -> Dict[str, int]:
        """
        Build summary counters from pending temporary layers (duplicates unknown → 0).

        Used when the import summary dock was closed but temporary layers remain.
        """
        summary_data: Dict[str, int] = {
            "csv_points_count": 0,
            "features_count": 0,
            "objects_count": 0,
            "small_finds_count": 0,
            "csv_duplicates": 0,
            "features_duplicates": 0,
            "objects_duplicates": 0,
            "small_finds_duplicates": 0,
        }
        mapping = (
            ("Imported_CSV_Points", "csv_points_count"),
            ("New Features", "features_count"),
            ("New Objects", "objects_count"),
            ("New Small Finds", "small_finds_count"),
        )
        for layer_name, key in mapping:
            layer = self._layer_service.get_layer_by_name(layer_name)
            if layer is not None and hasattr(layer, "featureCount"):
                summary_data[key] = int(layer.featureCount())
        return summary_data

    def _apply_configured_map_theme(self, settings_key: str) -> None:
        """Apply a configured map theme to the main QGIS project when set."""
        if not self._map_theme_service:
            return
        theme = self._settings_manager.get_value(settings_key, '')
        if theme:
            self._map_theme_service.apply_theme_to_current_project(theme, self._iface)
    
    def _handle_import_data_accepted(self, dialog) -> None:
        """Handle the case when import data dialog is accepted."""
        try:
            self._apply_configured_map_theme('import_map_theme')

            # Get selected items
            selected_csv_files = dialog.get_selected_csv_files()
            selected_completed_projects = dialog.get_selected_completed_projects()

            # Drop stale archive tracking for data types not part of this import session.
            if not selected_csv_files:
                self._csv_import_service.clear_last_imported_files()
            if not selected_completed_projects:
                self._field_project_import_service.clear_last_imported_projects()
            
            from qgis.PyQt.QtWidgets import QMessageBox
            
            # Initialize summary data
            summary_data = {
                'csv_points_count': 0,
                'features_count': 0,
                'objects_count': 0,
                'small_finds_count': 0,
                'csv_duplicates': 0,
                'features_duplicates': 0,
                'objects_duplicates': 0,
                'small_finds_duplicates': 0
            }

            csv_imported = False
            projects_imported = False
            
            # Process CSV files if any are selected
            if selected_csv_files:
                csv_result = self._process_csv_files(selected_csv_files)
                if csv_result is not None:
                    csv_imported = True
                    summary_data['csv_points_count'] = csv_result
                    csv_stats = self._csv_import_service.get_last_import_stats()
                    summary_data['csv_duplicates'] = csv_stats.get('csv_duplicates', 0)
            
            # Process completed projects if any are selected
            if selected_completed_projects:
                project_stats = self._process_completed_projects(selected_completed_projects)
                if project_stats:
                    projects_imported = True
                    summary_data.update(project_stats)
            
            # Show summary dialog if any data was imported
            if (summary_data['csv_points_count'] > 0 or
                summary_data['csv_duplicates'] > 0 or
                summary_data['features_count'] > 0 or 
                summary_data['objects_count'] > 0 or 
                summary_data['objects_duplicates'] > 0 or
                summary_data.get('duplicate_objects_warnings') or
                summary_data['small_finds_count'] > 0):
                
                self._show_import_summary(
                    summary_data,
                    archive_csv=csv_imported,
                    archive_projects=projects_imported,
                )
            
        except Exception as e:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Error"),
                self.tr(f"An error occurred during import data processing:\n{str(e)}")
            )
    
    def _process_csv_files(self, csv_files: List[str]) -> Optional[int]:
        """Process CSV files for import."""
        from qgis.PyQt.QtWidgets import QMessageBox
        
        # Validate CSV files
        validation_result = self._csv_import_service.validate_csv_files(csv_files)
        if not validation_result.is_valid:
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("CSV Validation Error"),
                validation_result.message
            )
            return None
        
        # Get column mapping and all headers
        column_mapping, file_columns = self._csv_import_service.get_column_mapping_and_headers(csv_files)
        
        # Check if columns differ across files
        columns_differ = False
        for column_name, column_list in column_mapping.items():
            if len(set(column_list)) > 1:  # More than one unique column name
                columns_differ = True
                break
        
        # If columns differ, show column mapping dialog
        if columns_differ:
            mapping_dialog = ColumnMappingDialog(
                column_mapping=column_mapping,
                csv_files=csv_files,
                file_columns=file_columns,
                parent=self._iface.mainWindow()
            )
            
            if self._execute_dialog(mapping_dialog) != mapping_dialog.Accepted:
                return None  # User cancelled
            
            # Get final mapping from dialog
            column_mapping = mapping_dialog.get_final_mapping()

        # Topo CSV: resolve which column fills ``identifier`` when ambiguous
        id_check = self._csv_import_service.check_csv_identifier_column_requirement(
            csv_files, column_mapping
        )
        if not id_check.is_valid:
            if getattr(id_check, "code", None) == "CSV_IDENTIFIER_AMBIGUOUS":
                candidates = (id_check.extras or {}).get("candidates") or []
                if not candidates:
                    QMessageBox.critical(
                        self._iface.mainWindow(),
                        self.tr("CSV Import Error"),
                        id_check.message,
                    )
                    return None
                from .ui.csv_identifier_column_dialog import CsvIdentifierColumnDialog
                dlg = CsvIdentifierColumnDialog(
                    parent=self._iface.mainWindow(),
                    candidates=candidates,
                    initial_selection=self._settings_manager.get_value(
                        "csv_topo_identifier_column", ""
                    )
                    or "",
                )
                if self._execute_dialog(dlg) != dlg.Accepted:
                    return None
                choice = dlg.selected_column_key()
                self._settings_manager.set_value("csv_topo_identifier_column", choice)
                import_result = self._csv_import_service.import_csv_files(
                    csv_files, column_mapping, identifier_source_column_key=choice
                )
            else:
                QMessageBox.critical(
                    self._iface.mainWindow(),
                    self.tr("CSV Import Error"),
                    id_check.message,
                )
                return None
        else:
            import_result = self._csv_import_service.import_csv_files(csv_files, column_mapping)

        if import_result.is_valid:
            return self._csv_import_service.get_last_import_count()
        else:
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("CSV Import Error"),
                import_result.message
            )
            return None
    
    def _process_completed_projects(self, project_paths: List[str]) -> Optional[Dict[str, int]]:
        """Process completed field projects for import."""
        from qgis.PyQt.QtWidgets import QMessageBox
        
        # Import field projects using the field project import service
        import_result = self._field_project_import_service.import_field_projects(project_paths)
        
        if import_result.is_valid:
            # Return the import statistics
            return self._field_project_import_service.get_last_import_stats()
        else:
            QMessageBox.critical(
                self._iface.mainWindow(),
                self.tr("Field Project Import Error"),
                import_result.message
            )
            return None
    
    def _show_import_summary(
        self,
        summary_data: Dict[str, int],
        *,
        archive_csv: bool = True,
        archive_projects: bool = True,
    ) -> None:
        """
        Show the import summary dock widget.

        The dock is created first so users can interact immediately, then warning
        detectors are triggered asynchronously through the dock refresh pipeline.
        This avoids long UI freezes before the panel appears on large imports.
        """
        try:
            from .ui.import_summary_dialog import (
                ImportSummaryDockWidget,
                ImportSummaryData,
                DOCK_WIDGET_AREAS,
            )
            # Drop any previous summary dock so we never show stale counts or warning layouts
            # (e.g. reopening Import with pending layers used to only raise_() an old dock).
            existing_summary = self._find_existing_import_summary_dock_widget()
            if existing_summary is not None:
                self._iface.removeDockWidget(existing_summary)
                existing_summary.deleteLater()
                QCoreApplication.processEvents()

            # Create summary data
            summary = ImportSummaryData(
                csv_points_count=summary_data.get('csv_points_count', 0),
                features_count=summary_data.get('features_count', 0),
                objects_count=summary_data.get('objects_count', 0),
                small_finds_count=summary_data.get('small_finds_count', 0),
                csv_duplicates=summary_data.get('csv_duplicates', 0),
                features_duplicates=summary_data.get('features_duplicates', 0),
                objects_duplicates=summary_data.get('objects_duplicates', 0),
                small_finds_duplicates=summary_data.get('small_finds_duplicates', 0),
                alternative_objects_merged_count=summary_data.get('alternative_objects_merged_count', 0),
                is_global_project=bool(summary_data.get('is_global_project', False)),
            )
            
            # Preserve any precomputed warnings passed in summary_data.
            summary.duplicate_objects_warnings = summary_data.get('duplicate_objects_warnings', [])
            summary.skipped_numbers_warnings = summary_data.get('skipped_numbers_warnings', [])
            summary.out_of_bounds_warnings = summary_data.get('out_of_bounds_warnings', [])
            summary.distance_warnings = summary_data.get('distance_warnings', [])
            summary.missing_total_station_warnings = summary_data.get('missing_total_station_warnings', [])
            summary.duplicate_total_station_identifiers_warnings = summary_data.get(
                'duplicate_total_station_identifiers_warnings', []
            )
            summary.height_difference_warnings = summary_data.get('height_difference_warnings', [])
            
            # Create and show the dock widget
            dock_widget = ImportSummaryDockWidget(
                summary, 
                iface=self._iface, 
                settings_manager=self._settings_manager,
                csv_import_service=self._csv_import_service,
                field_project_import_service=self._field_project_import_service,
                layer_service=self._layer_service,
                archive_csv=archive_csv,
                archive_projects=archive_projects,
                parent=self._iface.mainWindow()
            )
            
            # Add the dock widget to the main window
            self._iface.addDockWidget(DOCK_WIDGET_AREAS.right, dock_widget)

            # Let Qt paint the dock first, then run warning detectors silently.
            QCoreApplication.processEvents()
            QTimer.singleShot(0, dock_widget.refresh_warnings_silently)
            
        except Exception as e:
            print(f"Error showing import summary: {e}")
            import traceback
            traceback.print_exc()

    def _find_existing_import_summary_dock_widget(self):
        """
        Find an existing import summary dock widget attached to the main window.

        Returns:
            The existing dock widget if found, None otherwise.
        """
        try:
            main_window = self._iface.mainWindow()
            if not main_window:
                print("Debug: No main window found")
                return None

            dock_widgets = main_window.findChildren(QDockWidget)

            for child in dock_widgets:
                if hasattr(child, "__class__") and "ImportSummaryDockWidget" in child.__class__.__name__:
                    return child

                title = child.windowTitle()
                if title in ["Import Summary", self.tr("Import Summary")]:
                    return child

            return None

        except Exception as e:
            print(f"Error finding existing import summary dock widget: {e}")
            return None

    @property
    def settings_manager(self):
        """Get the settings manager instance."""
        return self._settings_manager
    
    @property
    def layer_service(self):
        """Get the layer service instance."""
        return self._layer_service
    

    
    @property
    def project_creation_service(self):
        """Get the project creation service instance."""
        return self._project_creation_service
    
    @property
    def csv_import_service(self):
        """Get the CSV import service instance."""
        return self._csv_import_service 