# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArcheoSyncDialog
                                 A QGIS plugin
 This plugin allows archaeologists to prepare data for the field and to import it back into the project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-01
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Elisa Caron-Laviolette
        email                : elisa.laviolette@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt


class ArcheoSyncDialog(QtWidgets.QDialog):
    """
    ArcheoSync Dialog - Pure PyQt implementation.
    
    This dialog provides the interface for the ArcheoSync plugin,
    allowing archaeologists to prepare data for the field and import it back.
    """
    
    def __init__(self, parent=None):
        """
        Initialize the ArcheoSync dialog.
        
        Args:
            parent: Parent widget for the dialog
        """
        super(ArcheoSyncDialog, self).__init__(parent)
        
        # Set dialog properties
        self.setWindowTitle("ArcheoSync")
        self.setGeometry(0, 0, 400, 300)
        
        # Create the main layout
        self.setup_ui()
        
        # Connect signals
        self.setup_connections()
    
    def setup_ui(self):
        """Set up the user interface components."""
        # Create main layout
        main_layout = QtWidgets.QVBoxLayout(self)
        
        # Add content area (placeholder for future widgets)
        content_widget = QtWidgets.QWidget()
        content_layout = QtWidgets.QVBoxLayout(content_widget)
        
        # Add a label as placeholder content
        placeholder_label = QtWidgets.QLabel("ArcheoSync Plugin")
        placeholder_label.setAlignment(Qt.AlignCenter)
        content_layout.addWidget(placeholder_label)
        
        # Add content widget to main layout
        main_layout.addWidget(content_widget)
        
        # Create button box
        self.button_box = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel,
            Qt.Horizontal,
            self
        )
        
        # Add button box to main layout
        main_layout.addWidget(self.button_box)
    
    def setup_connections(self):
        """Set up signal connections."""
        # Connect button box signals to dialog slots
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
